# Site settings
title: "Ben Force"
description: "Ben Force's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ben Force"
resume_title:                   "DevSecOps Security Assurance Expert"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "theRealBenForce@gmail.com?subject=I visited your website!"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Phoenix, Arizona"

resume_header_contact_info:     ""
display_header_contact_info:    "true"

resume_header_intro: "In my current role, I work closely with a small team of DevSecOps Assurance Experts to integrate automated security solutions into our CICD pipelines. This permits me to deepen my security expertise while also allowing me to crossover into cloud engineering and focus on Developer Experience, two areas I'm deeply passionate about.

<p>More recently, I dedicated significant time to enhancing my company's ServiceNow Service Portal. I take pride in having both personally conducted the user research and performed the ServiceNow development. This was an interesting detour in my career that game me new perspective on the platform capabilities and underlying architecture.</p>

<p>I possess a deep understanding of AWS and its best practices, having played a crucial engineering role in the early stages of our enterprise cloud transformation program. This experience introduced me to modern infrastructure management concepts such as IAC, CICD, cloud operating model, GitOps, and containerized workloads. I've also spent significant time as an engineer on the Horizon and Workspace ONE paltforms.</p>

<p>As evident, I have held various IT roles and have developed the ability and reputation of being able to quickly learn new technology domains.</p>

<p>In my personal life, I have been happily married for several years to a wonderful woman I met on my first day at Vanguard. We have an adorably goofy dog. I am also a home automation enthusiast working with the Home Assistant platform, a retro video game fanatic, and a passionate cook with a New Year's resolution to create two new dinners every week.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
resume_section_certs:           true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/theRealBenForce"
  #resume_twitter_url:           "http://twitter.com/name"
  #resume_dribbble_url:          "https://dribbble.com/name"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/theRealBenForce"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://benforce.io"
  #resume_medium_url:            "https://medium.com/r"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
