# Site settings
title: "Ben Force"
description: "Ben Force's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ben Force"
resume_title:                   "Senior Enterprise Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "theRealBenForce@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "In my current role, I am among a few who engineer and manage End User Computing services on the VMware Anywhere Workspace Platform. This consists of a variety virtual desktop (VDI) use cases and over 10,000 corporate and BYOD mobile devices.
<p>What sets me apart on my team is my experience integrating our reference architectures into other platforms, such as AWS, ServiceNow, Splunk, and PagerDuty. I'm also the lead developer for all code required to support our operations. I have a deep understanding of AWS and its best practices, and I played a critical engineering role in the first few years of our enterprise cloud transformation program.
<p>Recently, I've spent a lot of time incorporating our service offerings into ServiceNow. This involved learning the Now platform, developing a relationship with our internal platform team, and creating new service catalog offerings for an ever-evolving End User Computing space while supporting those left behind from a bygone era.
<p>As my experience shows, I am a highly versatile senior engineer that loves learning new technologies and motivating junior engineers."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_certs:           true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/theRealBenForce"
  #resume_twitter_url:           "http://twitter.com/name"
  #resume_dribbble_url:          "https://dribbble.com/name"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/theRealBenForce"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://benforce.io"
  #resume_medium_url:            "https://medium.com/r"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
