# Site settings
title: "Ben Force"
description: "Ben Force's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ben Force"
resume_title:                   "Solutions Consultant"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "theRealBenForce@gmail.com?subject=I visited your website!"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "In my current role I collaborate within a small team of engineers, UX designers, and UX researchers to improve the day to day lives of our crew through technology. We strive to reduce digital fatigue from crew so they can focus on the moments that matter most.</p>
<p>Recently, I've spent a lot of time improving our ServiceNow Service Portal. This involves developing relationships with process and service owners, reading user feedback, conducting interviews and research, and driving change through our development pipeline. Yes, I do the ServiceNow development myself!</p>
<p>Prior to this I spent a number of years working on our Virtual Desktop (VDI) platform and got quite familiar with this unique area of enterprise technology. This is where I first began learning the Now platform so that we could respond quickly to impacts in our workflows due to changes in the way we operate and adjustments to policy during the global pandemic.</p>
<p>I also have a deep understanding of AWS and its best practices. I played a critical engineering role in the first few years of our enterprise cloud transformation program. This was where I was first introduced to modern infrastructure management concepts such as IAC, CICD, cloud operating model, gitops, and containerized workloads.</p>
<p>As you can see, I've had a lot of very different jobs in IT and pride myself on being able to learn new technology domains quickly.</p>
<p>In my personal life, I'm happily married of several years now to a wonderful woman I met on my first day of work at Vanguard. We have a very silly dog. I'm also a home automation enthusiast who works on the Home Assistant platform and retro videogame fanatic. I love to cook and my new year resolution is to make two new dinners every week.</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_certs:           true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/theRealBenForce"
  #resume_twitter_url:           "http://twitter.com/name"
  #resume_dribbble_url:          "https://dribbble.com/name"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/theRealBenForce"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://benforce.io"
  #resume_medium_url:            "https://medium.com/r"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
